# Values for ip-lookup application
replicaCount: 1

image:
  repository: chrisleekr/ip-lookup
  tag: "1.0.0"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    # Enable HTTPS
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Add security headers
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-XSS-Protection: 1; mode=block";
    # Force HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: "ip-lookup.local"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ip-lookup-tls
      hosts:
        - ip-lookup.local

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
