name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  NODE_VERSION: '22'
  # Using Ubuntu 22.04 LTS (Jammy Jellyfish) for long-term stability
  # This version is supported until April 2027
  RUNNER_VERSION: 'ubuntu-22.04'

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  prepare:
    runs-on: ${{ env.RUNNER_VERSION }}
    if: "!contains(github.event.head_commit.message, 'chore(main): release')"
    timeout-minutes: 15
    outputs:
      cache-hit: ${{ steps.npm-cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
        id: npm-cache

      - name: Install dependencies
        run: npm ci
        if: steps.npm-cache.outputs.cache-hit != 'true'

  lint:
    needs: prepare
    runs-on: ${{ env.RUNNER_VERSION }}
    if: "!contains(github.event.head_commit.message, 'chore(main): release')"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        if: needs.prepare.outputs.cache-hit != 'true'

      - name: Run linter
        run: npm run lint

  lint-dockerfile:
    runs-on: ${{ env.RUNNER_VERSION }}
    if: "!contains(github.event.head_commit.message, 'chore(main): release')"
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  test:
    needs: prepare
    runs-on: ${{ env.RUNNER_VERSION }}
    if: "!contains(github.event.head_commit.message, 'chore(main): release')"
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        if: needs.prepare.outputs.cache-hit != 'true'

      - name: Run tests
        run: npm run test -- --ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
          retention-days: 2

  build:
    needs: prepare
    runs-on: ${{ env.RUNNER_VERSION }}
    if: "!contains(github.event.head_commit.message, 'chore(main): release')"
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        if: needs.prepare.outputs.cache-hit != 'true'

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7

  docker:
    needs: [build, lint, test]
    runs-on: ${{ env.RUNNER_VERSION }}
    if: "!contains(github.event.head_commit.message, 'chore(main): release')"
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=dev-
            type=raw,value=cache,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=ip-lookup
            org.opencontainers.image.description=IP information lookup service
            org.opencontainers.image.vendor=${{ github.repository_owner }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false # Do not push dev images into the registry
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            BUILD_DATE=${{ github.event.repository.updated_at }}
            COMMIT_SHA=${{ github.sha }}

  security:
    needs: docker
    runs-on: ${{ env.RUNNER_VERSION }}
    if: "github.ref != 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(main): release')"
    timeout-minutes: 20
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev-${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          timeout: '5m'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
